apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/cart:303
        ports:              # port where your container listens
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        envFrom:  
          - configMapRef:
              name: cart-cm
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-cm 
data:
  CATALOGUE_HOST: "catalogue-svc"
  REDIS_HOST: "roboshop-dev-redis.8m1fwx.0001.use1.cache.amazonaws.com"
--- 
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8080              
      targetPort: 8080   

--- 

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75